name: Build code, run unit test, run SAST, SCA, DAST security scans
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Zap auth 
    steps:
    - name: Login zap
      run: |
        docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j -t http://testphp.vulnweb.com -r testreport.html --hook=/zap/auth_hook.py -z "auth.loginurl=http://testphp.vulnweb.com/login.php auth.username="test" auth.password="test""
